name: Release on demand

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Version to release (i.e., 1.3.2)"
        required: true
      snapshotVersion:
        description: "Snapshot version after release (i.e., 1.3.3-SNAPSHOT)"
        required: true

jobs:
  call-release:
    uses: clojure/build.ci/.github/workflows/release.yml@master
    with:
      releaseVersion: ${{ github.event.inputs.releaseVersion }}
      snapshotVersion: ${{ github.event.inputs.snapshotVersion }}
    secrets: inherit